import { useState, useEffect } from "react";
import { jwtDecode } from "jwt-decode"; // Install: npm install jwt-decode

const UseAuth = () => {
  const [token, setToken] = useState(localStorage.getItem("authToken"));
  const [user, setUser] = useState(null);
  const [isAdmin, setIsAdmin] = useState(false);
  const [loading, setLoading] = useState(true); // New state

  const handleToken = (token) => {
    try {
      const decodedToken = jwtDecode(token);

      // Check for token expiration
      if (decodedToken.exp && decodedToken.exp * 1000 < Date.now()) {
        throw new Error("Token expired");
      }

      setUser(decodedToken);

      // ** Update isAdmin based on userType from the token payload **
      // Assuming the userType property exists in the token payload as generated by your backend
      const adminStatus = decodedToken.userType === "ADMIN";
      setIsAdmin(adminStatus);

    } catch (error) {
      console.error("Invalid or expired token:", error.message);
      // Clear invalid token and reset state
      localStorage.removeItem("authToken");
      setToken(null);
      setUser(null);
      setIsAdmin(false);
    } finally {
      // Set loading to false after token processing
      setLoading(false);
    }
  };

  useEffect(() => {
    const storedToken = localStorage.getItem("authToken");
    if (storedToken) {
      setToken(storedToken);
      handleToken(storedToken);
    } else {
      // If no token is stored, set initial state accordingly
      setToken(null);
      setUser(null);
      setIsAdmin(false);
      setLoading(false); // Ensure loading is false if no token is found
    }
  }, []); // Empty dependency array means this runs only once on mount

  const login = (newToken) => {
    localStorage.setItem("authToken", newToken);
    setToken(newToken);
    handleToken(newToken); // Process the new token
  };

  const logout = () => {
    localStorage.removeItem("authToken");
    setToken(null);
    setUser(null);
    setIsAdmin(false);
    setLoading(false); // Set loading to false on logout
  };

  return { token, user, isAdmin, login, logout, loading };
};

export default UseAuth;
